import React, { useState, useMemo, useEffect } from "react";
import {
  ScatterChart, Scatter, XAxis, YAxis, ZAxis, CartesianGrid, Tooltip,
  ReferenceArea, ReferenceLine, ResponsiveContainer,
} from "recharts";
import { Database, FlaskConical, Info, AlertTriangle, Layers, Filter } from "lucide-react";

/*
  Satoru — Residue Compare
  Wired to the ORA corpus (corpus.json generated by pipeline/05_export.py).
  Falls back to "illustrative data" banner when corpus.json is absent.

  Invariants (do not break):
   1. Default view is Δ¹³C (baseline-robust). Scatter view carries an explicit baseline caveat.
   2. Reference fields are NAMED and CITED on the plot — not baked in invisibly.
   3. Tool PLOTS and CONTEXTUALISES. It does not classify. "Plots within X field" ≠ "is X".
   4. Aquatic caveat is always visible: Δ¹³C cannot resolve aquatic/marine from non-ruminant.
   5. Every backend point carries provenance (citation + site) on hover.
   6. Backend points are muted (slate). User points are amber.
   7. Illustrative banner disappears only once real data is loaded.
*/

// ─── Palette ─────────────────────────────────────────────────────────────────
const INK       = "#13233B";
const INK_SOFT  = "#2B405C";
const PAPER     = "#F4F6F8";
const AMBER     = "#D8961F";
const AMBER_DEEP = "#A86A0E";
const SLATE     = "#7C8DA3";

const BAND = {
  nonrum:  { label: "Non-ruminant adipose", fill: "#E7E2D6", text: "#6B5E3E" },
  adipose: { label: "Ruminant adipose",     fill: "#D6DCD2", text: "#4F6248" },
  dairy:   { label: "Ruminant dairy",       fill: "#C7D2DC", text: "#2E4A63" },
};

// ─── Thresholds (Copley et al. 2003; Evershed et al. 2008) ───────────────────
const T_NONRUM = -1.0;
const T_DAIRY  = -3.1;

const D16_MIN = -34, D16_MAX = -22;
const DELTA_MIN = -7, DELTA_MAX = 2;
const D18_MIN = -38, D18_MAX = -22;

const ALL_REGIONS = ["Britain", "Ireland"];
const ALL_PERIODS = [
  "Early Neolithic",
  "Middle Neolithic",
  "Late Neolithic",
  "Neolithic (unspec)",
];

// ─── User input parsing ───────────────────────────────────────────────────────
function parseInput(text) {
  const rows = [], errors = [];
  text.split("\n").forEach((raw, i) => {
    const line = raw.trim();
    if (!line || line.startsWith("#")) return;
    const parts = line.split(/[,\t]| {2,}/).map(s => s.trim()).filter(Boolean);
    let label, a, b;
    if (parts.length >= 3)      { [label, a, b] = parts; }
    else if (parts.length === 2) { label = `S${rows.length + 1}`; [a, b] = parts; }
    else { errors.push({ line: i + 1, msg: "need label, δ¹³C16:0, δ¹³C18:0" }); return; }
    const d16 = parseFloat(a), d18 = parseFloat(b);
    if (!isFinite(d16) || !isFinite(d18)) { errors.push({ line: i + 1, msg: "values are not numbers" }); return; }
    if (d16 > 0 || d18 > 0 || d16 < -50 || d18 < -50) { errors.push({ line: i + 1, msg: "δ¹³C values look out of range" }); return; }
    rows.push({ id: label, d16, d18, delta: +(d18 - d16).toFixed(2) });
  });
  return { rows, errors };
}

function bandOf(delta) {
  if (delta > T_NONRUM) return "nonrum";
  if (delta < T_DAIRY)  return "dairy";
  return "adipose";
}

const SAMPLE_INPUT =
`# label, δ¹³C16:0, δ¹³C18:0   (one sample per line)
MY-01, -28.9, -32.6
MY-02, -27.2, -29.0
MY-03, -26.1, -26.4`;

// ─── Corpus loading ───────────────────────────────────────────────────────────
function useCorpus() {
  const [corpus, setCorpus] = useState(null);  // null = loading; [] = loaded (may be empty)
  const [loadError, setLoadError] = useState(null);

  useEffect(() => {
    fetch("/corpus.json")
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then(data => setCorpus(data))
      .catch(err => {
        console.warn("corpus.json not found — showing illustrative data:", err.message);
        setLoadError(err.message);
        setCorpus({ meta: { record_count: 0, sources: [] }, records: [] });
      });
  }, []);

  return { corpus, loadError };
}

// ─── App ─────────────────────────────────────────────────────────────────────
export default function App() {
  const [tab, setTab]             = useState("delta");
  const [raw, setRaw]             = useState(SAMPLE_INPUT);
  const [committed, setCommitted] = useState(SAMPLE_INPUT);
  const [regions, setRegions]     = useState(new Set(ALL_REGIONS));
  const [periods, setPeriods]     = useState(new Set(ALL_PERIODS));

  const { corpus, loadError } = useCorpus();
  const isIllustrative = !corpus || corpus.meta.record_count === 0;

  // Map corpus records to plot shape
  const allBackend = useMemo(() => {
    if (!corpus) return [];
    return corpus.records.map(r => ({
      id:          r.id,
      d16:         r.d16,
      d18:         r.d18,
      delta:       r.delta,
      site:        r.site,
      region:      r.region,
      period:      r.period,
      ceramic_type: r.ceramic_type,
      citation:    r.citation,
      doi:         r.doi,
      table_fig:   r.table_fig,
      author_assignment: r.author_assignment,
    }));
  }, [corpus]);

  // Apply region + period filters
  const filteredBackend = useMemo(() =>
    allBackend.filter(r => regions.has(r.region) && periods.has(r.period)),
    [allBackend, regions, periods],
  );

  // Illustrative fallback data (used when corpus.json not present)
  const ILLUSTRATIVE = useMemo(() => [
    ["WH-114", -29.4, -33.0, "Windmill Hill"],
    ["WH-118", -28.7, -32.5, "Windmill Hill"],
    ["HH-203", -27.9, -31.6, "Hambledon Hill"],
    ["HH-211", -28.2, -32.1, "Hambledon Hill"],
    ["WH-126", -29.0, -32.8, "Windmill Hill"],
    ["GW-31",  -27.1, -30.0, "Grooved Ware vessel"],
    ["GW-40",  -26.6, -29.2, "Grooved Ware vessel"],
    ["EN-09",  -28.8, -31.3, "Early Neolithic carinated bowl"],
    ["PB-55",  -26.0, -26.6, "Peterborough Ware"],
    ["PB-58",  -25.4, -25.9, "Peterborough Ware"],
  ].map(([id, d16, d18, site]) => ({
    id, d16, d18, delta: +(d18 - d16).toFixed(2),
    site, region: "Britain", period: "Neolithic (unspec)",
    ceramic_type: "unknown", citation: "illustrative — not real data",
    doi: "", table_fig: "",
  })), []);

  const backendPoints = isIllustrative ? ILLUSTRATIVE : filteredBackend;

  const { rows: userRows, errors } = useMemo(() => parseInput(committed), [committed]);

  const backDelta   = backendPoints.map(r => ({ ...r, x: r.d16, y: r.delta }));
  const backScatter = backendPoints.map(r => ({ ...r, x: r.d16, y: r.d18 }));
  const userDelta   = userRows.map(r => ({ ...r, x: r.d16, y: r.delta }));
  const userScatter = userRows.map(r => ({ ...r, x: r.d16, y: r.d18 }));

  function toggleSet(setter, value) {
    setter(prev => {
      const next = new Set(prev);
      next.has(value) ? next.delete(value) : next.add(value);
      return next;
    });
  }

  return (
    <div className="sat-root">
      <style>{css}</style>

      <header className="sat-head">
        <div className="sat-brand">
          <span className="sat-seal">悟</span>
          <div>
            <div className="sat-title">Residue Compare</div>
            <div className="sat-sub">Single-compound δ¹³C · British &amp; Irish Neolithic</div>
          </div>
        </div>
        {isIllustrative && (
          <span className="sat-flag"><AlertTriangle size={13} /> Illustrative data — run pipeline/05_export.py</span>
        )}
        {!isIllustrative && (
          <span className="sat-live">
            {corpus.meta.record_count.toLocaleString()} records ·{" "}
            {corpus.meta.sources.length} studies
          </span>
        )}
      </header>

      <div className="sat-grid">
        {/* ── Left panel ── */}
        <aside className="sat-panel">
          <div className="sat-eyebrow"><FlaskConical size={13} /> Your samples</div>
          <textarea
            className="sat-input"
            value={raw}
            spellCheck={false}
            onChange={e => setRaw(e.target.value)}
          />
          <button className="sat-btn" onClick={() => setCommitted(raw)}>
            Plot my samples
          </button>

          {errors.length > 0 && (
            <div className="sat-errors">
              {errors.map((e, i) => <div key={i}>Line {e.line}: {e.msg}</div>)}
            </div>
          )}

          <div className="sat-eyebrow mt"><Database size={13} /> Reference set</div>
          <p className="sat-cite">
            Δ¹³C thresholds −1.0 and −3.1‰ after{" "}
            <a href="https://doi.org/10.1073/pnas.0335955100" target="_blank" rel="noreferrer">
              Copley et al. 2003
            </a>{" "}
            and{" "}
            <a href="https://doi.org/10.1073/pnas.0709640104" target="_blank" rel="noreferrer">
              Evershed et al. 2008
            </a>
            . NW-European C3 reference frame. Match the reference set to your
            samples' isoscape.
          </p>

          {!isIllustrative && (
            <>
              <div className="sat-eyebrow mt"><Filter size={13} /> Filter corpus</div>
              <div className="sat-filters">
                <div className="sat-filter-group">
                  <div className="sat-filter-label">Region</div>
                  {ALL_REGIONS.map(r => (
                    <label key={r} className="sat-checkbox">
                      <input
                        type="checkbox"
                        checked={regions.has(r)}
                        onChange={() => toggleSet(setRegions, r)}
                      />
                      {r}
                    </label>
                  ))}
                </div>
                <div className="sat-filter-group">
                  <div className="sat-filter-label">Period</div>
                  {ALL_PERIODS.map(p => (
                    <label key={p} className="sat-checkbox">
                      <input
                        type="checkbox"
                        checked={periods.has(p)}
                        onChange={() => toggleSet(setPeriods, p)}
                      />
                      {p}
                    </label>
                  ))}
                </div>
              </div>
              <p className="sat-cite">
                Showing {filteredBackend.length} of {allBackend.length} corpus records.
              </p>
            </>
          )}

          <div className="sat-note">
            <Info size={13} />
            <span>
              This tool plots where your samples fall relative to published reference
              fields. It does <b>not</b> classify them. Field membership is context,
              not identification.
            </span>
          </div>

          <div className="sat-note aquatic">
            <AlertTriangle size={13} />
            <span>
              <b>Aquatic caveat:</b> Δ¹³C alone cannot resolve aquatic or marine fats
              from non-ruminant adipose — they overlap. Separation requires biomarker
              evidence (isoprenoid acids, C20/C22 APAAs) not captured here.
              Particularly relevant for samples from coastal or estuarine contexts
              (cf. Cramp et al. 2014).
            </span>
          </div>
        </aside>

        {/* ── Plot area ── */}
        <main className="sat-main">
          <div className="sat-tabs">
            <button className={tab === "delta" ? "on" : ""} onClick={() => setTab("delta")}>
              <Layers size={13} /> Δ¹³C view
            </button>
            <button className={tab === "scatter" ? "on" : ""} onClick={() => setTab("scatter")}>
              δ¹³C16:0 vs δ¹³C18:0
            </button>
          </div>

          {tab === "scatter" && (
            <div className="sat-caveat">
              <AlertTriangle size={13} />
              Raw δ¹³C values carry the environmental baseline (climate, canopy, C3/C4
              mix, period). If your samples come from a different isoscape, separation
              here can mislead. The Δ¹³C view strips the common baseline and is the
              safer comparison.
            </div>
          )}

          <div className="sat-chartwrap">
            <ResponsiveContainer width="100%" height="100%">
              <ScatterChart margin={{ top: 12, right: 96, bottom: 44, left: 8 }}>
                <CartesianGrid stroke="#dfe4ea" strokeDasharray="2 4" />
                <XAxis
                  type="number" dataKey="x" name="δ¹³C16:0"
                  domain={[D16_MIN, D16_MAX]}
                  tick={{ fill: INK_SOFT, fontSize: 11, fontFamily: "mono" }}
                  stroke={INK_SOFT}
                  label={{ value: "δ¹³C16:0 (‰)", position: "bottom", offset: 18, fill: INK, fontSize: 12 }}
                />
                <YAxis
                  type="number" dataKey="y"
                  domain={tab === "delta" ? [DELTA_MIN, DELTA_MAX] : [D18_MIN, D18_MAX]}
                  tick={{ fill: INK_SOFT, fontSize: 11, fontFamily: "mono" }}
                  stroke={INK_SOFT}
                  label={{
                    value: tab === "delta" ? "Δ¹³C = δ18:0 − δ16:0 (‰)" : "δ¹³C18:0 (‰)",
                    angle: -90, position: "insideLeft", offset: 18, fill: INK, fontSize: 12,
                    style: { textAnchor: "middle" },
                  }}
                />
                <ZAxis range={[60, 60]} />

                {tab === "delta" ? (
                  <>
                    <ReferenceArea y1={T_DAIRY}  y2={DELTA_MIN} fill={BAND.dairy.fill}   fillOpacity={0.85} />
                    <ReferenceArea y1={T_NONRUM} y2={T_DAIRY}   fill={BAND.adipose.fill} fillOpacity={0.85} />
                    <ReferenceArea y1={DELTA_MAX} y2={T_NONRUM} fill={BAND.nonrum.fill}  fillOpacity={0.85} />
                    <ReferenceLine y={T_DAIRY}  stroke="#9bb0c4" strokeDasharray="4 3"
                      label={{ value: "−3.1", position: "right", fill: BAND.dairy.text,   fontSize: 10 }} />
                    <ReferenceLine y={T_NONRUM} stroke="#b9b193" strokeDasharray="4 3"
                      label={{ value: "−1.0", position: "right", fill: BAND.adipose.text, fontSize: 10 }} />
                  </>
                ) : (
                  <>
                    <ReferenceLine
                      segment={[{ x: D16_MIN, y: D16_MIN + T_NONRUM }, { x: D16_MAX, y: D16_MAX + T_NONRUM }]}
                      stroke="#b9b193" strokeDasharray="5 3"
                      label={{ value: "Δ −1.0", position: "insideTopRight", fill: BAND.adipose.text, fontSize: 10 }} />
                    <ReferenceLine
                      segment={[{ x: D16_MIN, y: D16_MIN + T_DAIRY }, { x: D16_MAX, y: D16_MAX + T_DAIRY }]}
                      stroke="#9bb0c4" strokeDasharray="5 3"
                      label={{ value: "Δ −3.1", position: "insideBottomRight", fill: BAND.dairy.text, fontSize: 10 }} />
                  </>
                )}

                <Tooltip content={(props) => <Dot {...props} isIllustrative={isIllustrative} />} cursor={{ strokeDasharray: "3 3" }} />

                <Scatter
                  name={isIllustrative ? "Reference corpus (illustrative)" : "ORA corpus"}
                  data={tab === "delta" ? backDelta : backScatter}
                  fill={SLATE} fillOpacity={0.45} shape="circle"
                />
                <Scatter
                  name="Your samples"
                  data={tab === "delta" ? userDelta : userScatter}
                  fill={AMBER} stroke={AMBER_DEEP} strokeWidth={1.5} shape="diamond"
                />
              </ScatterChart>
            </ResponsiveContainer>

            {tab === "delta" && (
              <div className="sat-strata">
                <span style={{ color: BAND.nonrum.text }}>{BAND.nonrum.label}</span>
                <span style={{ color: BAND.adipose.text }}>{BAND.adipose.label}</span>
                <span style={{ color: BAND.dairy.text }}>{BAND.dairy.label}</span>
              </div>
            )}
          </div>

          <div className="sat-ref-cite">
            Reference bands: Copley et al. 2003 (PNAS); Evershed et al. 2008 (PNAS) ·
            NW-European C3 reference frame
          </div>

          <div className="sat-legend">
            <span><i className="dot amber" /> Your samples</span>
            <span>
              <i className="dot slate" />{" "}
              {isIllustrative
                ? <em>Illustrative corpus — not real extracted data (run pipeline/05_export.py)</em>
                : <>ORA corpus ({filteredBackend.length} records — hover for provenance)</>
              }
            </span>
          </div>

          {userRows.length > 0 && (
            <table className="sat-table">
              <thead>
                <tr>
                  <th>SAMPLE</th><th style={{textTransform:"none"}}>δ¹³C16:0</th><th style={{textTransform:"none"}}>δ¹³C18:0</th><th style={{textTransform:"none"}}>Δ¹³C</th><th>PLOTS WITHIN</th>
                </tr>
              </thead>
              <tbody>
                {userRows.map(r => {
                  const b = BAND[bandOf(r.delta)];
                  const isNearBoundary = Math.abs(r.delta - T_NONRUM) < 1.0 || Math.abs(r.delta - T_DAIRY) < 0.5;
                  return (
                    <tr key={r.id}>
                      <td className="mono">{r.id}</td>
                      <td className="mono">{r.d16.toFixed(1)}</td>
                      <td className="mono">{r.d18.toFixed(1)}</td>
                      <td className="mono">{r.delta.toFixed(2)}</td>
                      <td>
                        <span className="chip" style={{ background: b.fill, color: b.text }}>
                          {b.label} field
                        </span>
                        {isNearBoundary && bandOf(r.delta) === "nonrum" && (
                          <span className="aquatic-warn" title="Aquatic caveat applies — see left panel">
                            ⚠ aquatic possible
                          </span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}

          {userRows.length > 0 && (
            <p className="sat-disclaim">
              "Plots within … field" describes position relative to the reference set only.
              It is not an identification of the commodity processed — that interpretation,
              with its caveats, stays with you.
            </p>
          )}
        </main>
      </div>

      <footer className="sat-foot">
        <span>
          Code: open source (MIT) · Dataset:{" "}
          <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC-BY 4.0</a>
          {" "}with per-record source attribution · Cite Satoru + the original studies.
        </span>
        <span className="mono">悟 Satoru · DigiShield Labs</span>
      </footer>
    </div>
  );
}

// ─── Tooltip ─────────────────────────────────────────────────────────────────
function Dot({ active, payload, isIllustrative }) {
  if (!active || !payload?.length) return null;
  const p = payload[0].payload;
  const isUser = !p.citation || p.citation === undefined;

  return (
    <div className="sat-tip">
      <div className="sat-tip-id">{p.id}</div>
      <div className="mono">
        δ16:0 {p.d16?.toFixed(1)} · δ18:0 {p.d18?.toFixed(1)} · Δ {p.delta?.toFixed(2)}‰
      </div>
      {isUser ? (
        <div className="sat-tip-src">your sample</div>
      ) : (
        <>
          <div className="sat-tip-src">{p.citation}</div>
          {p.site && <div className="sat-tip-src">Site: {p.site}</div>}
          {p.period && <div className="sat-tip-src">{p.period}</div>}
          {p.ceramic_type && p.ceramic_type !== "unknown" && (
            <div className="sat-tip-src">{p.ceramic_type}</div>
          )}
          {p.region && <div className="sat-tip-src">{p.region}</div>}
          {p.table_fig && <div className="sat-tip-src">{p.table_fig}</div>}
          {isIllustrative && (
            <div className="sat-tip-src" style={{ color: "#f5c066" }}>
              ⚠ illustrative — not real data
            </div>
          )}
        </>
      )}
    </div>
  );
}

// ─── CSS ──────────────────────────────────────────────────────────────────────
const css = `
.sat-root{--ink:${INK};--amber:${AMBER};font-family:ui-sans-serif,system-ui,"Segoe UI",Roboto,sans-serif;
  color:${INK};background:${PAPER};border:1px solid #e1e6ec;border-radius:14px;overflow:hidden;max-width:1120px;margin:0 auto}
.sat-root .mono{font-family:ui-monospace,"SF Mono",Menlo,Consolas,monospace}
.sat-head{display:flex;align-items:center;justify-content:space-between;padding:16px 20px;background:${INK};color:#fff}
.sat-brand{display:flex;align-items:center;gap:12px}
.sat-seal{display:grid;place-items:center;width:34px;height:34px;border-radius:50%;border:1.5px solid ${AMBER};
  color:${AMBER};font-size:18px;line-height:1}
.sat-title{font-size:16px;font-weight:650;letter-spacing:.2px}
.sat-sub{font-size:11px;color:#9fb0c6;font-family:ui-monospace,monospace;letter-spacing:.3px}
.sat-flag{display:inline-flex;align-items:center;gap:5px;font-size:11px;color:#1a1205;background:${AMBER};
  padding:4px 9px;border-radius:999px;font-weight:600}
.sat-live{font-size:11px;color:#9fb0c6;font-family:ui-monospace,monospace}
.sat-grid{display:grid;grid-template-columns:300px 1fr;gap:0}
@media(max-width:760px){.sat-grid{grid-template-columns:1fr}}
.sat-panel{padding:18px;border-right:1px solid #e1e6ec;background:#fbfcfd;overflow-y:auto;max-height:780px}
.sat-eyebrow{display:flex;align-items:center;gap:6px;font-size:11px;font-weight:700;text-transform:uppercase;
  letter-spacing:.9px;color:${INK_SOFT};margin-bottom:8px}
.sat-eyebrow.mt{margin-top:20px}
.sat-input{width:100%;height:118px;resize:vertical;border:1px solid #cfd6df;border-radius:8px;padding:9px 10px;
  font-family:ui-monospace,monospace;font-size:12px;color:${INK};background:#fff;box-sizing:border-box}
.sat-input:focus{outline:2px solid ${AMBER};border-color:${AMBER}}
.sat-btn{margin-top:9px;width:100%;background:${INK};color:#fff;border:0;border-radius:8px;padding:9px;
  font-size:13px;font-weight:600;cursor:pointer}
.sat-btn:hover{background:${INK_SOFT}}
.sat-errors{margin-top:9px;font-size:11.5px;color:#8a3b2e;background:#fbe9e6;border:1px solid #f0c8c1;
  border-radius:7px;padding:7px 9px;line-height:1.5}
.sat-filters{display:flex;flex-direction:column;gap:10px;margin-bottom:6px}
.sat-filter-group{display:flex;flex-direction:column;gap:4px}
.sat-filter-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:#8893a3;margin-bottom:2px}
.sat-checkbox{display:flex;align-items:center;gap:7px;font-size:12px;cursor:pointer;color:${INK_SOFT}}
.sat-checkbox input{accent-color:${AMBER}}
.sat-cite{font-size:10.5px;color:#7c8696;line-height:1.55;margin:8px 0 0}
.sat-cite a{color:${INK_SOFT};text-decoration:underline dotted}
.sat-note{display:flex;gap:7px;align-items:flex-start;margin-top:14px;font-size:11.5px;line-height:1.55;
  color:${INK_SOFT};background:#eef2f6;border-radius:8px;padding:10px}
.sat-note svg{flex:none;margin-top:1px;color:${AMBER_DEEP}}
.sat-note.aquatic{background:#fdf6e3;border:1px solid #f0d798}
.sat-note.aquatic svg{color:#c07c00}
.sat-main{padding:16px 18px 4px}
.sat-tabs{display:flex;gap:6px;margin-bottom:10px}
.sat-tabs button{display:inline-flex;align-items:center;gap:6px;border:1px solid #d4dae2;background:#fff;color:${INK_SOFT};
  border-radius:8px;padding:7px 12px;font-size:12.5px;font-weight:600;cursor:pointer}
.sat-tabs button.on{background:${INK};color:#fff;border-color:${INK}}
.sat-caveat{display:flex;gap:7px;align-items:flex-start;font-size:11.5px;line-height:1.5;color:#6b4a16;
  background:#fbf2dd;border:1px solid #ecd9a8;border-radius:8px;padding:9px 11px;margin-bottom:10px}
.sat-caveat svg{flex:none;margin-top:1px;color:${AMBER_DEEP}}
.sat-chartwrap{position:relative;height:400px}
.sat-strata{position:absolute;right:2px;top:12px;bottom:56px;display:flex;flex-direction:column;
  justify-content:space-between;align-items:flex-end;font-size:9.5px;font-weight:700;letter-spacing:.3px;
  text-transform:uppercase;text-align:right;pointer-events:none;width:90px}
.sat-ref-cite{font-size:9.5px;color:#9aa4b2;padding:2px 2px 0;text-align:right}
.sat-legend{display:flex;gap:18px;flex-wrap:wrap;font-size:11.5px;color:${INK_SOFT};padding:4px 2px 0}
.sat-legend em{color:#9aa4b2;font-style:italic}
.sat-legend .dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px;vertical-align:middle}
.sat-legend .amber{background:${AMBER}}
.sat-legend .slate{background:${SLATE}}
.sat-table{width:100%;border-collapse:collapse;margin-top:14px;font-size:12px}
.sat-table th{text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.6px;color:#8893a3;
  border-bottom:1px solid #dde3ea;padding:6px 8px}
.sat-table td{padding:6px 8px;border-bottom:1px solid #eef1f5}
.sat-table .chip{display:inline-block;padding:2px 9px;border-radius:999px;font-size:11px;font-weight:600}
.aquatic-warn{margin-left:7px;font-size:10px;color:#8a5c00;background:#fef3cd;
  padding:1px 6px;border-radius:999px;font-weight:600}
.sat-disclaim{font-size:10.5px;color:#7c8696;line-height:1.55;margin:8px 2px 12px}
.sat-tip{background:${INK};color:#fff;border-radius:8px;padding:8px 10px;font-size:11.5px;box-shadow:0 6px 18px rgba(0,0,0,.2);max-width:220px}
.sat-tip-id{font-weight:700;margin-bottom:2px}
.sat-tip .mono,.sat-tip-src{color:#b9c6d6;font-size:10.5px;margin-top:2px}
.sat-foot{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:12px 20px;
  background:#fbfcfd;border-top:1px solid #e1e6ec;font-size:10.5px;color:#7c8696}
.sat-foot .mono{color:${INK_SOFT}}
.sat-foot a{color:${INK_SOFT};text-decoration:underline dotted}
`;
